<div class="d-flex border p-3 rounded">
    <div>
        <img id="image_preview" class="avatar rounded img-thumbnail" src="<?= $this->current_user->avatar()->path() ?>" alt="avatar">

        <form action="<?= route('profile.avatar') ?>" method="POST" enctype="multipart/form-data">
            <input id="image_preview_input" type="file" name="user_avatar" id="user_avatar">
            <div class="d-grid mt-2">
                <button id="image_preview_submit" type="submit" class="btn btn-fill btn-primary">Atualizar</button>
            </div>
        </form>

        <?php if ($this->current_user->avatar_name) : ?>
            <form action="<?= route('profile.avatar.remove') ?>" method="POST">
                <input type="hidden" name="_method" value="PUT">  
                <div class="d-grid mt-2">
                    <button id="remove_image" type="submit" class="btn btn-fill btn-primary">Remover</button>
                </div>
            </form>
        <?php endif ?>

    </div>
    <div class="mx-5">
        <div class="rounded">
            <h3><?= $this->current_user->name ?></h3>
            <span class="text-primary"><?= $this->current_user->responsibility ?></span>
        </div>
        <ul class="list-unstyled mt-2">
            <li>
                <span>Email: <?= $this->current_user->email ?></span>
            </li>
        </ul>
    </div>
</div>