<h1 class="fs-3"><?= $title ?></h1>

<div class="d-flex justify-content-end mb-3">
    <a href="<?=route('users.new') ?>" class="btn btn-primary">Novo Usuário</a>
</div>

<table class="table table-striped table-hover align-middle border">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Cargo</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?=$user->name ?></td>
                <td><?=$user->email ?></td>
                <td><?=$user->responsibility ?></td>
                <td>
                    <div class="d-flex justify-content-end gap-3">
                        <a href="<?= route('users.show', ['id' => $user->id]) ?>">
                            <button class="btn btn-link p-0">
                                <span class="material-symbols-outlined" style="color: lightblue;">
                                    visibility
                                </span>
                            </button>
                        </a>

                        <a href="<?= route('users.edit', ['id' => $user->id]) ?>">
                            <button class="btn btn-link p-0">
                                <span class="material-symbols-outlined" style="color: orange;">
                                    edit
                                </span>
                            </button>
                        </a>

                        <form action="<?= route('users.destroy', ['id' => $user->id]) ?>" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            
                            <button type="submit" class="btn btn-link p-0">
                                <span class="material-symbols-outlined" style="color: red;">
                                    delete
                                </span>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        <? endforeach ?>
    </tbody>
</table>


<?php $paginator->renderPagesNavigation(); ?>