<h1 class="fs-3"><?= $title ?></h1>

<div class="d-flex justify-content-end mb-3">
    <a href="<?=route('tables.new') ?>" class="btn btn-primary">Nova mesa</a>
</div>

<table class="table table-striped table-hover align-middle border">
    <thead>
        <tr>
            <th>Número</th>
            <th>Link</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($tables as $table) : ?>
            <tr>
                <td><?=$table->table_number ?></td>
                <td>
                    <?php
                        $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
                        
                        $host = $_SERVER['HTTP_HOST'];
                        
                        echo $protocol . $host . $table->link_token ;
                    ?>
                </td>
                
                <td><?=$table->created_at ?></td>
                <td>
                    <div class="d-flex justify-content-end gap-3">
                        <a href="<?= route('tables.edit', ['id' => $table->id]) ?>">
                            <button class="btn btn-link p-0">
                                <span class="material-symbols-outlined" style="color: orange;">
                                    edit
                                </span>
                            </button>
                        </a>

                        <form action="<?= route('tables.destroy', ['id' => $table->id]) ?>" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            
                            <button type="submit" class="btn btn-link p-0">
                                <span class="material-symbols-outlined" style="color: red;">
                                    delete
                                </span>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        <? endforeach ?>
    </tbody>
</table>


<?php $paginator->renderPagesNavigation(); ?>