<?php foreach (\Lib\FlashMessage::get() as $type => $msg) : ?>
    <div>
        <button type="button" class="d-none" id="liveToastBtn">Show live toast</button>
        
        <div 
            id="liveToast"
            class="toast align-items-center text-bg-<?= $type ?> border-0 position-fixed top-0 end-0 m-3"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
        >
            <div class="d-flex">
                <div class="toast-body">
                    <?= $msg ?>
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>

        <script>
            const toastTrigger = document.getElementById('liveToastBtn')
            const toastLiveExample = document.getElementById('liveToast')

            if (toastTrigger) {
                const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample)
                toastTrigger.addEventListener('click', () => {
                    toastBootstrap.show()
                })
                
                toastTrigger.click()
            }
        </script>
    </div>
<? endforeach ?>